# Generated by Django 5.0.2 on 2024-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('msp', 'Msp'), ('msp_org', 'Msp_Org')], max_length=20)),
                ('is_client', models.BooleanField(default=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('organisation_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('short_name', models.CharField(max_length=255)),
                ('dar_logo', models.CharField(max_length=255)),
                ('light_logo', models.CharField(max_length=255)),
                ('auth_type', models.CharField(choices=[('sso', 'Sso'), ('login', 'Login')], default='login', max_length=20)),
                ('parent_msp_id', models.BigIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
