# Generated by Django 5.0.2 on 2024-02-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ec2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('private_dns_name', models.CharField(max_length=255)),
                ('private_ip_address', models.CharField(max_length=50)),
                ('public_dns_name', models.CharField(max_length=255)),
                ('public_ip_address', models.CharField(max_length=50)),
                ('instance_name', models.CharField(max_length=255, unique=True)),
                ('instance_id', models.CharField(max_length=100)),
                ('aws_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(max_length=255, null=True)),
                ('organisation_type', models.CharField(choices=[('msp', 'MSP'), ('direct', 'DIRECT'), ('msp_org', 'MSP_ORF')], default='direct', max_length=20)),
                ('is_client', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=20)),
                ('domain_name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=20)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('dark_logo', models.CharField(max_length=255, null=True)),
                ('light_logo', models.CharField(max_length=255, null=True)),
                ('auth_type', models.CharField(choices=[('sso', 'SSO'), ('login', 'LOGIN')], default='login', max_length=20)),
                ('parent_msp_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vpc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('vpc_id', models.CharField(max_length=100)),
                ('cidr', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Elastic_Ips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('private_ip', models.CharField(max_length=45, null=True)),
                ('reverse_dns', models.CharField(max_length=255, null=True)),
                ('elastic_ip_type', models.CharField(choices=[('Public IP', 'PUBLIC_IP'), ('Private IP', 'PRIVATE_IP')], default='Public IP', max_length=20, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('ec2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceapp.ec2')),
                ('organisation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceapp.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Elastic_Ips_Ec2_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elastic_ip_str', models.CharField(max_length=255, null=True)),
                ('ec2_id_str', models.CharField(max_length=255, null=True)),
                ('ec2_status', models.CharField(max_length=100, null=True)),
                ('elastic_ip_status', models.CharField(max_length=255)),
                ('ec2_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceapp.ec2')),
                ('elastic_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.elastic_ips')),
            ],
        ),
        migrations.AddField(
            model_name='ec2',
            name='organisation_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resourceapp.organisation'),
        ),
        migrations.AddField(
            model_name='ec2',
            name='vpc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.vpc'),
        ),
    ]
