# Generated by Django 5.0.2 on 2024-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpc',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
