# Generated by Django 5.0.2 on 2024-02-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2',
            name='instance_type',
            field=models.CharField(max_length=1000),
        ),
    ]
