# Generated by Django 5.0.2 on 2024-02-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0002_alter_organisations_dar_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='dar_logo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='light_logo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
