# Generated by Django 5.0.2 on 2024-02-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0003_alter_organisations_dar_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='dar_logo',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='light_logo',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
