# Generated by Django 5.0.2 on 2024-02-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0004_alter_organisations_dar_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='parent_msp_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
