# Generated by Django 5.0.2 on 2024-02-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0005_alter_organisations_parent_msp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ec2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpc_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('instance_id', models.CharField(max_length=255)),
                ('instance_type', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('instance_status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped')], default='stopped', max_length=20)),
                ('public_dns', models.CharField(max_length=255)),
                ('public_ip', models.CharField(max_length=255)),
                ('private_ip', models.CharField(max_length=255)),
                ('agent_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='disconnected', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.organisations')),
            ],
        ),
    ]
