# Generated by Django 5.0.2 on 2024-02-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0006_ec2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElastipIps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('private_ip', models.CharField(max_length=45)),
                ('reverse_dns', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Public IP', 'Public_Ip'), ('Private', 'Private_Ip')], default=None, max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('ec2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.ec2')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.organisations')),
            ],
        ),
    ]
