# Generated by Django 5.0.2 on 2024-02-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0007_elastipips'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticIps_Ec2_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=20)),
                ('ec2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.ec2')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.organisations')),
            ],
        ),
    ]
