# Generated by Django 5.0.2 on 2024-02-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0008_elasticips_ec2_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSConfigurationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('access_key', models.TextField()),
                ('secret_key', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.organisations')),
            ],
        ),
    ]
