# Generated by Django 5.0.2 on 2024-02-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourceapp', '0010_vpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('group_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('ec2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.ec2')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.organisations')),
                ('vpc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourceapp.vpc')),
            ],
        ),
    ]
